# Generated by Django 4.2.23 on 2025-08-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.AddField(
            model_name='size',
            name='categories',
            field=models.ManyToManyField(related_name='sizes', to='products.category'),
        ),
    ]
